{
 "title": "Nacos-注册",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "命名空间",
    "query": "label_values(probe_success{}, namespace)"
   },
   {
    "name": "instance",
    "label": "服务",
    "query": "label_values(probe_success{namespace=~\"$namespace\"}, instance)"
   },
   {
    "name": "hostname",
    "label": "主机名",
    "query": "label_values(probe_success{namespace=~\"$namespace\"}, hostname)"
   },
   { "name": "interval", "label": "时间间隔", "query": "30s,1m,2m,3m,5m,10m,30m" }
  ]
 },
 "panels": [
  {
   "title": "实例数量",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(probe_success{job=\"nacos-java-process\"}) by (instance)"
    }
   ]
  },
  {
   "title": "使用命名空间",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(count(probe_success{job=\"nacos-java-process\"}) by (namespace))"
    }
   ]
  },
  {
   "title": "注册实例数量",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(probe_success{job=\"nacos-java-process\"})"
    }
   ]
  },
  {
   "title": "注册服务",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(count(probe_success{job=\"nacos-java-process\"}) by (service))"
    }
   ]
  },
  {
   "title": "服务器数量",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(count(label_replace(probe_success{job=\"nacos-java-process\"},\"ip\",\"$1\",\"address\",\"(.*):.*\")) by (ip))"
    }
   ]
  },
  {
   "title": "Nacos状态",
   "type": "table",
   "gridPos": { "h": 18, "w": 17, "x": 7, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "probe_success{job=\"nacos-java-process\",namespace=~\"$namespace\",instance=~\"$instance\",hostname=~\"$hostname\"}"
    }
   ]
  },
  {
   "title": "服务器数量",
   "type": "table",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "count(label_replace(probe_success{job=\"nacos-java-process\"},\"ip\",\"$1\",\"address\",\"(.*):.*\"))  by (ip,hostname)"
    }
   ]
  },
  { "title": "资源使用", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "CPU使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$hostname\",mode=\"system\"}[$interval])) by (instance) *100",
     "legendFormat": "{{ instance }}系统使用率"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$hostname\",mode=\"user\"}[$interval])) by (instance) *100",
     "legendFormat": "{{ instance }}用户使用率"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$hostname\",mode=\"iowait\"}[$interval])) by (instance) *100",
     "legendFormat": "{{ instance }}磁盘IO使用率"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{instance=~\"$hostname\",mode=\"idle\"}[$interval])) by (instance))*100",
     "legendFormat": "{{ instance }}总使用率"
    }
   ]
  },
  {
   "title": "内存信息",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$hostname\"}",
     "legendFormat": "{{ instance }}总内存"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$hostname\"} - node_memory_MemAvailable_bytes{instance=~\"$hostname\"}",
     "legendFormat": "{{ instance }}已用"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$hostname\"}",
     "legendFormat": "{{ instance }}可用"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$hostname\"} / (node_memory_MemTotal_bytes{instance=~\"$hostname\"})))* 100",
     "legendFormat": "{{ instance }}使用率"
    }
   ]
  },
  {
   "title": "每秒磁盘读写容量",
   "type": "graph",
   "description": "Read bytes 每个磁盘分区每秒读取的比特数\nWritten bytes 每个磁盘分区每秒写入的比特数",
   "gridPos": { "h": 8, "w": 8, "x": 15, "y": 21 },
   "yaxes": [
    { "format": "Bps", "label": "读取（-）/写入（+）" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=~\"$hostname\"}[$interval])",
     "legendFormat": "{{ instance }}_{{device}}_读取"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{instance=~\"$hostname\"}[$interval])",
     "legendFormat": "{{ instance }}_{{device}}_写入"
    }
   ]
  },
  {
   "title": "网络Socket连接信息",
   "type": "graph",
   "description": "Sockets_used - 已使用的所有协议套接字总量\n\nCurrEstab - 当前状态为 ESTABLISHED 或 CLOSE-WAIT 的 TCP 连接数\n\nTCP_alloc - 已分配（已建立、已申请到sk_buff）的TCP套接字数量\n\nTCP_tw - 等待关闭的TCP连接数\n\nUDP_inuse - 正在使用的 UDP 套接字数量\n\nRetransSegs - TCP 重传报文数\n\nOutSegs - TCP 发送的报文数\n\nInSegs - TCP 接收的报文数",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~'$hostname'}",
     "legendFormat": "{{ instance }} CurrEstab"
    },
    {
     "expr": "node_sockstat_TCP_tw{instance=~'$hostname'}",
     "legendFormat": "{{ instance }} TCP_tw"
    },
    {
     "expr": "node_sockstat_sockets_used{instance=~'$hostname'}",
     "legendFormat": "{{ instance }} Sockets_used"
    },
    {
     "expr": "node_sockstat_UDP_inuse{instance=~'$hostname'}",
     "legendFormat": "{{ instance }} UDP_inuse"
    },
    {
     "expr": "node_sockstat_TCP_alloc{instance=~'$hostname'}",
     "legendFormat": "{{ instance }} TCP_alloc"
    },
    {
     "expr": "rate(node_netstat_Tcp_InSegs{instance=~'$hostname'}[$interval])",
     "legendFormat": "{{ instance }} Tcp_InSegs"
    },
    {
     "expr": "rate(node_netstat_Tcp_OutSegs{instance=~'$hostname'}[$interval])",
     "legendFormat": "{{ instance }} Tcp_OutSegs"
    },
    {
     "expr": "rate(node_netstat_Tcp_RetransSegs{instance=~'$hostname'}[$interval])",
     "legendFormat": "{{ instance }} Tcp_RetransSegs"
    }
   ]
  }
 ]
}